config/routes.rb
GooglePlace::Application.routes.draw do
  root 'places#index'
  get 'places' => 'places#search', as: 'locations'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  require 'net/http'
  respond_to :json

  def index
	  if params[:search].present?
	  end
	end

	def search
		main = 'https://maps.googleapis.com/maps/api/place/textsearch/json?'
    key = ENV['key'] || 'AIzaSyCQw1mWQj1SDFHHhAL7buDnrWbs72n4FM4'
    query = { query: params[:search],
    	types: 'street_address',
    	sensor: 'false',
    	key: key
    }.to_query

    query = main + query

		url = URI.parse(query)

		response = Net::HTTP.start(url.host,
		  use_ssl: true,
		  verify_mode: OpenSSL::SSL::VERIFY_NONE) do |http|
      http.get url.request_uri
    end
    reply = JSON.parse response.body
    @results = reply['results']
    @error_message = reply['error_message']
    logger.debug "========>#{reply} "  

  	respond_to :js
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GooglePlace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_results.html.erb
<p>
  <b style='color: red;'><%= @error_message %></b>
</p>

</br>
<%- if @results.present? %>
	<%- @results.each do |result| %>
	  <p>
	    <b>Address :</b>  <%= result['formatted_address'] %>
	  </p>
	<%-end%>
<%- else %>
  <b>No Result found.</b>	
<%-end%>

app/views/places/index.html.erb
Search for places near a given address.

<%= form_tag locations_path, method: :get, remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search],
     autofocus: true, placeholder: 'Address' %>
    <%= submit_tag "Search Near", id: 'submit' %>
  </p>
<% end %>
<hr>
<h2>Results</h2>
<div id='results'/>

app/views/places/search.js.erb
$('#results').html('<%=j render 'places/results' %>');